<nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top">
	<a class="navbar-brand" href="<?= $this->url('home') ?>">
		<img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>" />&nbsp;Skeleton Application
	</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav mr-auto">
            <?php
            $navHelper = $this->navigation('navigation')
                ->setAcl($this->acl)
                ->setRole('guest');
            $containers = $navHelper->getContainer();
            foreach ($containers->getpages() as $page) {
                $class = "";
                if ($page->isActive()) {
                    $class = "active";
                }
                
                if (count($page)) {
                    $label = $page->getLabel();
                    $label = $this->translate($label);
                    $label = $this->escapehtml($label);
                    printf('<li class="nav-item dropdown %s">' . "\n", ($class ? '' . $class : ''));
                    printf('<a href="%s" class="nav-link dropdown-toggle" data-toggle="dropdown">%s<b class="caret"></b></a>' . "\n", $page->getHref(), $label);
                    echo '<div class="dropdown-menu" aria-labelledby="navbarDropdown">' . "\n";
                    
                    foreach ($page as $subPage) {
                        if (! $navHelper->accept($subPage)) {
                            continue;
                        }
                        printf('<a class="dropdown-item">%s</a>' . "\n", $navHelper->htmlify($subPage));
                    }
                    echo '</div></li>' . "\n";
                } else {
                    printf('<li class="nav-item %s"><a class="nav-link" href="%s">%s</a></li>' . "\n", $class, $page->getHref(), $page->getLabel());
                }
            }
            ?>
        </ul>
	</div>
</nav>